version: "3.9"

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./src:/var/www/app

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - php
    volumes:
      - ./src/:/var/www/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    ports:
      - "33006:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: ./.docker/redis/Dockerfile
    ports:
      - "63790:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./.docker/redis/data:/data
      - ./.docker/redis/redis.conf:/etc/redis.conf
